# -*- coding: utf-8 -*-
"""web_scraping2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLrPAzpqN-gSO5HUzVi9ijNK7Y8w2225
"""

# author: Evan Collins
# created: 3/31/21
# IDCE302

# A web scraper to search a practice book catalogue and print out the books with one star ratings.
# The scraper accesses the URL, parses the text, selects and sorts out the one star titles, then prints the resulting list. 

import requests
import bs4

base_url = "http://books.toscrape.com/catalogue/page-{}.html"

# initiate an empty list that will hold the output.
one_star_titles = []

# Now iterate to get info from each page.
# Include only pages 1-5, so index should go up to, but not include 6.
for n in range (1,6):
  scrape_url = base_url.format(n)
  res = requests.get(scrape_url)
  soup = bs4.BeautifulSoup(res.text,'lxml')
  books = soup.select(".product_pod")
  # Within the loop, another loop to parse the books and select one star ratings.
  for book in books:
    if len(book.select('.star-rating.One')) != 0: # if the list is not empty, then it is a 1 star book.
      book_title = book.select('a')[1]['title']
      one_star_titles.append(book_title)
      
one_star_titles

